services:
    unzeroun_sorter.applier.array:
        class: UnZeroUn\Sorter\Applier\ArrayApplier
        tags:  [ { name: unzeroun_sorter.applier } ]

    unzeroun_sorter.applier.doctrine_orm:
        class: UnZeroUn\Sorter\Applier\DoctrineORMApplier
        tags:  [ { name: unzeroun_sorter.applier } ]

    unzeroun_sorter.factory:
        class:     UnZeroUn\Sorter\SorterFactory
        arguments: [[]]

    unzeroun_sorter.builder.url:
        class: UnZeroUn\Sorter\Builder\UrlBuilder

    unzeroun_sorter.extension.twig.sort:
        class:     UnZeroUn\Sorter\Bundle\Extension\Twig\SortExtension
        arguments: [ '@unzeroun_sorter.builder.url', '@request_stack' ]
        tags:      [ { name: twig.extension } ]
